### ISSUE TITLE
Make run on full db error

### ISSUE THREAD

**Issue by teuncortooms** [FontysMarioPizzaCase/import#24]
When doing 'make run' on a full db (without 'make stop') then I get this error. Does Github Actions also test this testcase? Do you get the same error?

![image](https://user-images.githubusercontent.com/4932561/112772654-424c6700-9032-11eb-839f-d969c028eb3c.png)

**Comment by mdevrees** [comment]
Please check the amount of memory that's assigned to your instances.

**Comment by MrDienns** [comment]
On teams you mentioned you have 2GB allocated to Docker on your Windows laptop;

That is, 2 GB for an entire Linux virtual machine (since Windows is not Unix based, it cannot re-use the host system), plus import application (Java is already very lazy with memory cleanups, plus there's a lot of data flowing through), and a PostgreSQL database. 2 GB likely simply won't cut it, and there's nothing we can do about that. Increase your local memory allocation from Docker to at least 8 GB or so, or at least in that direction.
